"""added location column to organization model

Revision ID: 297b68daf55c
Revises: 04ddef375f87
Create Date: 2023-03-28 15:46:28.116289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297b68daf55c'
down_revision = '04ddef375f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
