"""added role and is_active attributes to user_org join table

Revision ID: a1e4bbf9e14a
Revises: 7660474b5d0f
Create Date: 2023-03-27 09:43:47.658563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e4bbf9e14a'
down_revision = '7660474b5d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_organizations', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
